#	@(#)Makefile	8.1 (Berkeley) 6/5/93
# $FreeBSD: head/usr.sbin/route6d/Makefile 201390 2010-01-02 11:07:44Z ed $

PROG=	route6d
MAN=	route6d.8

CFLAGS+= -DHAVE_POLL_H

BINDIR=	/usr/local/sbin
MANDIR=	/usr/local/share/man/man

.include <bsd.prog.mk>
