#!/bin/sh

channels='2 8 10 32 42 53'
pause=20
mute=1

args=`getopt Ms: $*`
if [ $? != 0 ]
then
        echo 'Usage: channelsurf [-M] [-s pausetime]'
        exit 2
fi
set -- $args
for i
do
        case "$i"
        in
		-M)
			mute=0
			shift
			;;
                -s)
                        pause=$2
                        shift; shift
			;;
        esac
done

if [ ${mute} -ne 0 ] ; then
	vol=$(eyetv vol)
	eyetv vol 0
fi

for chan in ${channels} ; do
	eyetv channel ${chan}
	sleep ${pause}
done

if [ ${mute} -ne 0 ] ; then
	eyetv vol ${vol}
fi
