.Dd January 21, 2013
.\" 
.\" Copyright (c) 2013 Lyndon Nerenberg <lyndon@orthanc.ca>
.\" All rights reserved.
.\" 
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\" 
.\" THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE
.\" FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
.\" OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\" 
.Dt DVD 1 LOCAL
.Os
.Sh NAME
.Nm dvd
.Nd control the DVD Player application
.Sh SYNOPSIS
.Nm
.Ar command
.Op Ar arg
.Sh DESCRIPTION
The
.Nm
utility issues commands to the DVD Player application.
Invoking
.Nm
will cause the DVD Player to be launched if it is not already
running.
.Ss Commands
The following
.Ar command Ns s
are recognized:
.Pp
.Bl -tag -compact -width "audio [track] "
.It Li menu
Display the DVD's main menu.
.It Li title
Display the DVD's title menu.
.It Li play Op Ar title
Play (or un-pause) the DVD. Specify a numeric
.Ar title
to play that title.
.It Li pause
Pause the currently playing title.
.It Li stop
Stop playing the current title or menu.
.It Li next
Skip to the next chapter marker.
.It Li prev
Skip to the previous chapter marker.
.It Li chapter Ar chap
Skip to chapter
.Ar chap
in the current title.
.It Li vol Ar level
Set the DVD Player's volume to
.Ar level ,
in the range
.Em 0
(minimum) to
.Em 255
(maximum).
.It Li audio Op Ar track
Select the specified (numeric) audio track. If
.Ar track
is not given, display the DVD's audio menu.
.It Li full
Switch the player window into fullscreen mode.
.It Li nofull
Switch the player window out of fullscreen mode.
.It Li timeleft
Print the number of seconds remaining in the currently playing title.
.It Li restart
Re-initialize the state of the DVD, as if it had just been
inserted in the player.
.It Li enter Ns , Li up Ns , Li down Ns , Li left Ns , Li right
Press the corresponding button on the (virtual) DVD controller.
.It Li state Ns , Li status
Print the state of the DVD player. A partial list of values includes
.Sy stopped ,
.Sy paused ,
.Sy playing ,
and
.Sy playing still
(when displaying a DVD menu).
.It Li eject
Eject the DVD.
.El
.Sh RETURN VALUES
The
.Ic state
and
.Ic timeleft
commands print the values documented in their descriptions above. The
remaining commands print the value returned by the Applescript bridge
interface to the DVD Player application.
.Pp
The exit status of the
.Nm
utility is that of the underlying
.Xr osascript 1
command.
.Sh SEE ALSO
.Xr osascript 1 ,
.Xr vol 1
.Sh BUGS
The error messages returned by the Applescript bridge interface are
obtuse, at best.
